### PR TITLE
Update dpdk to 17.08, added mTCP module updates

### PR DESCRIPTION
**Pull request by koolzz**
This pr updates the dpdk version and the mTCP igb_uio.

How do we handle the licensing?

### CODE REVIEW

**Comment by twood02** [comment]
did you make any significant changes to the code?  If it is all minor stuff I say we just keep all licensing as is

**Comment by nks5295** [comment]
I'm investigating licensing now

**Comment by nks5295** [comment]
Since the DPDK files that they have modified do not contain any license changes (the DPDK files from their repo use the same license as the DPDK repo), we should just add to the README for the onvm branch of onvm-dpdk giving credit to mTCP authors for the features they have added to DPDK.

**Comment by twood02** [comment]
@koolzz can you add a change to the README file with something like:

```
This DPDK repository contains modifications and enhancements to work better with [OpenNetVM](https://github.com/sdnfv/openNetVM) and [mTCP](https://github.com/eunyoung14/mtcp). These changes were made by developers of the respective projects.
```

**Comment by koolzz** [comment]
@twood02 Done

**Pull request merged**
